### ISSUE TITLE
X12 package R - handling zero or negative values

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [statistikat/x12#14]
Hello, I am using x12work method from X12 package at the moment. I am getting the below error. I know it is due to some zeros in my series. Can we handle this anyway ?

` ERROR: Multiplicative or log-additive seasonal adjustment cannot be 
        done with a series with zero or negative values. `

**Comment by alexkowa** [comment]
Hello,
can you send me example code or at least the series with the specific problem. Otherwise it is hard to find the error.

**Comment by Jeeva-Ganesan** [comment]
Hi. This is the code I have used. `  x12out <- x12work(t,x12path="/Applications/x12arima/x12a",
                    transform.function="log", x11.type="sa",x11.samode = "mult")` . And yes my series has some "zeros" in it. Is it always the case that we cannot use multi decomposition with zeros ?

**Comment by alexkowa** [comment]
Hello, yes that is true, at the moment the error message is not read correctly into R, because I recently switched to a new backend (x13binary package). The error message is:
ERROR:   Multiplicative or log-additive seasonal adjustment cannot be done with a series with zero or negative values.
